/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Celda;
import Modelo.Ficha;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Felipe
 */
public class PanelCielo extends javax.swing.JPanel {

    Celda tunel[] = new Celda[7];
    Ficha fichas[][] = new Ficha[4][4];//fichas[i][j], i:color (0 rojo, 1 verde, 2 azul, 3 amarillo)

    /**
     * Creates new form PanelCielo
     */
    public PanelCielo() {
        initComponents();
        for (int i = 0; i < 7; i++) {
            tunel[i] = new Celda(10 + (35 * i), 10, 35, 105);
            tunel[i].setPosicion(69+i);
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        //Dibujar las celdas que son parte del camino al cielo
        for (int i = 0; i < tunel.length; i++) {
            g.drawRect(tunel[i].x, tunel[i].y, tunel[i].width, tunel[i].height);
            g.drawString(String.valueOf(tunel[i].getPosicion()), tunel[i].x, tunel[i].y);
        }
        //pintar imagen de cielo
        g.drawImage(new ImageIcon(getClass().getResource("../img/cielo.jpg")).getImage(), 260, 10, this);

        //pintar las fichas
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                if (fichas[i][j] != null) {
                    if (fichas[i][j].isSeleccionado()) {
                        g.drawImage(new ImageIcon(getClass().getResource("../img/seleccionado.png")).getImage(), fichas[i][j].x, fichas[i][j].y, this);
                    }
                    g.drawImage(new ImageIcon(getClass().getResource("../img/ficha" + i + ".png")).getImage(), fichas[i][j].x, fichas[i][j].y, this);
                }
            }
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
